version: '3.7'

services:
  django:
    deribit:
      context: .
      dockerfile: docker/local/Dockerfile
    volumes:
      - .:/app
    command: python -m unittest
    stdin_open: true
    tty: true
